version: '3'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - '80:80'
        depends_on:
            - portainer
            - pihole
            - heimdall
            - deluge
            - code
            - emby
            - radarr
            - sonarr
        networks:
            - phantom-net

    portainer:
        container_name: portainer
        image: portainer/portainer:latest
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${STORAGE}/homelab/portainer/data:/data
        expose:
            - '8000'
            - '9000'
        ports:
            - '9000:9000'
        networks:
            - phantom-net

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: always
        volumes:
            - '${STORAGE}/homelab/pihole/etc-pihole/:/etc/pihole/'
            - '${STORAGE}/homelab/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
        expose:
            - '80'
        environment:
            - TZ=Asia/Kolkata
        env_file:
            - ./pihole/pihole.env
        dns:
            - 127.0.0.1
            - 1.1.1.1
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            - phantom-net

    heimdall:
        container_name: heimdall
        image: linuxserver/heimdall:latest
        restart: unless-stopped
        volumes:
            - ./heimdall/config:/config # Issue with heimdall of UID=0
        expose:
            - '80'
        env_file:
            - ./linuxserver.env
        networks:
            - phantom-net

    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest
        restart: unless-stopped
        volumes:
            - ${STORAGE}/homelab/deluge/config:/config
            - ${STORAGE}/homelab/deluge/downloads:/downloads # Edit the Download directory in Preferences
        expose:
            - '8112'
        env_file:
            - ./linuxserver.env
        environment:
            - DELUGE_LOGLEVEL=error
        networks:
            - phantom-net

    code:
        container_name: code
        image: linuxserver/code-server:latest
        restart: unless-stopped
        volumes:
            - ${STORAGE}/homelab/code/project:/config
        expose:
            - '8443'
        env_file:
            - ./linuxserver.env
            - ./code/code.env
        # command: --base-path /code
        networks:
            - phantom-net

    emby:
        container_name: emby
        image: linuxserver/emby:latest
        restart: unless-stopped
        volumes:
            - ${STORAGE}/homelab/emby/config:/config
            - ${STORAGE}/movies:/movies
            - ${STORAGE}/tv:/tv
        expose:
            - '8096'
        ports:
            - '8096:8096'
        env_file:
            - ./linuxserver.env
        networks:
            - phantom-net

    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        volumes:
            - ${STORAGE}/homelab/radarr/config:/config
            - ${STORAGE}/movies:/movies
        expose:
            - '7878'
        env_file:
            - ./linuxserver.env
        networks:
            - phantom-net

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        volumes:
            - ${STORAGE}/homelab/sonarr/config:/config
            - ${STORAGE}/tv:/tv
        expose:
            - '8989'
        env_file:
            - ./linuxserver.env
        networks:
            - phantom-net

networks:
    phantom-net:
        external: true
