version: '3'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - '80:80'
        depends_on:
            - pihole
            - deluge
            - radarr
        networks:
            - phantom-net

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: always
        volumes:
            - '${STORAGE}/homelab/pihole/etc-pihole/:/etc/pihole/'
            - '${STORAGE}/homelab/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
        expose:
            - '80'
        environment:
            - TZ=Asia/Kolkata
        env_file:
            - ./pihole/pihole.env
        dns:
            - 127.0.0.1
            - 1.1.1.1
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            - phantom-net

    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest
        restart: unless-stopped
        volumes:
            - ${STORAGE}/homelab/deluge/config:/config
            - ${STORAGE}/homelab/deluge/downloads:/downloads # Edit the Download directory in Preferences
        expose:
            - '8112'
        env_file:
            - ./linuxserver.env
        environment:
            - DELUGE_LOGLEVEL=error
        networks:
            - phantom-net

    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        volumes:
            - ${STORAGE}/homelab/radarr/config:/config
            - ${STORAGE}/movies:/movies
            - ${STORAGE}/homelab/deluge/downloads:/downloads
        expose:
            - '7878'
        env_file:
            - ./linuxserver.env
        networks:
            - phantom-net

    tor:
        container_name: tor
        build: ./tor
        image: tor:latest
        restart: unless-stopped
        ports:
                - '9050:9050'
        networks:
            - phantom-net

networks:
    phantom-net:
        external: true
