version: '3'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/tilde-enhanced:/etc/nginx/html/:ro
        ports:
            - '80:80'
        depends_on:
            - portainer
            - pihole
            - heimdall
            - deluge
            - code
            - emby
            - radarr
            - sonarr
        networks:
            - phantom-net

    portainer:
        container_name: portainer
        image: portainer/portainer:latest
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer/data:/data
        expose:
            - '8000'
            - '9000'
        ports:
            - '9000:9000'
        networks:
            - phantom-net

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: always
        volumes:
            - './pihole/etc-pihole/:/etc/pihole/'
            - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
        expose:
            - '80'
        environment:
            - TZ=Asia/Kolkata
        env_file:
            - ./pihole/pihole.env
        dns:
            - 127.0.0.1
            - 1.1.1.1
        cap_add:
            - NET_ADMIN
        networks:
            - phantom-net

    heimdall:
        container_name: heimdall
        image: linuxserver/heimdall:latest
        restart: always
        volumes:
            - ./heimdall/config:/config
        expose:
            - '80'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        networks:
            - phantom-net

    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest
        restart: always
        volumes:
            - ./deluge/config:/config
            - $HOME/storage/deluge/downloads:/downloads # Edit the Download directory in Preferences
        expose:
            - '8112'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - UMASK_SET=022
            - DELUGE_LOGLEVEL=error
        networks:
            - phantom-net

    code:
        container_name: code
        image: codercom/code-server:arm64
        restart: always
        volumes:
            - ./code/project:/home/coder/project
        expose:
            - '8080'
        env_file:
            - ./code/code.env
        command: --base-path /code
        networks:
            - phantom-net

    emby:
        container_name: emby
        image: emby/embyserver_arm64v8:latest
        restart: always
        volumes:
            - $HOME/storage/emby/config:/config
            - $HOME/storage/movies:/movies
            - $HOME/storage/tv:/tv
        expose:
            - '8096'
            - '8920'
        ports:
            - '8096:8096'
        environment:
            - UID=1000
            - GID=1000
            - GIDLIST=1000
        networks:
            - phantom-net

    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: always
        volumes:
            - $HOME/storage/radarr/config:/config
            - $HOME/storage/movies:/movies
        expose:
            - '7878'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - UMASK_SET=022
        networks:
            - phantom-net

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: always
        volumes:
            - $HOME/storage/sonarr/config:/config
            - $HOME/storage/tv:/tv
        expose:
            - '8989'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - UMASK_SET=022
        networks:
            - phantom-net

networks:
    phantom-net:
        external: true
