version: "3"

services:
    code:
        container_name: code
        image: codercom/code-server:arm64
        expose:
            - "8080"
        volumes:
            - "./project:/home/coder/project"
            - ./local_share_code-server:/home/coder/.local/share/code-server"
        command: --base-path /code
        env_file:
            code.env
        networks:
            - phantom-net

networks:
    phantom-net:
        external: true
