version: '3'

services:
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - ./config:/config
        ports:
            - 80:80
        restart: unless-stopped
        networks:
            - phantom-net

networks:
    phantom-net:
        external: true
