version: '3'

services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    expose:
        - '8112'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=error
    volumes:
      - ./config:/config
      - $HOME/storage/deluge/downloads:/downloads # Edit the Download directory in Preferences
    restart: unless-stopped
    networks:
        - phantom-net

networks:
    phantom-net:
        external: true
