version: "3"

services:
    portainer:
        container_name: portainer
        image: portainer/portainer:latest
        ports:
            - "8000:8000"
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        restart: always
