version: "3"

services:
    portainer:
        container_name: portainer
        image: portainer/portainer:latest
        expose:
            - "8000"
            - "9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        restart: always
        networks:
            - phantom-net

networks:
    phantom-net:
        external: true
